"""Structured Pydantic v2 output models and schemas for AI Exception Investigation."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from src.domain.models import ScenarioType


class RecommendedAction(str, Enum):
    """Action recommendation determined by the AI investigator and ambiguity gate."""
    AUTO_RESOLVE = "AUTO_RESOLVE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    ESCALATE_FRAUD = "ESCALATE_FRAUD"


class CandidateScore(BaseModel):
    """Represents an alternative candidate scenario evaluated during investigation."""
    model_config = ConfigDict(validate_assignment=True)

    scenario_type: ScenarioType = Field(..., description="Hypothesized reconciliation scenario")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence in this scenario")
    rationale: str = Field(..., description="Financial justification for this candidate")


class EvidenceBundle(BaseModel):
    """Structured financial evidence package passed to the AI Investigator."""
    model_config = ConfigDict(validate_assignment=True)

    target_record_id: str = Field(..., description="ID of the anomalous/unmatched entity")
    target_record_type: str = Field(..., description="Type (e.g. BankStatementLine, APInvoice)")
    amount_cents: int = Field(..., description="Target amount in integer cents")
    date: Optional[str] = Field(default=None, description="ISO date of the transaction")
    description: Optional[str] = Field(default=None, description="Raw transaction memo/description")
    reference_code: Optional[str] = Field(default=None, description="Reference or wire code if available")
    candidate_matches: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Candidate counterparty records located within tolerance window"
    )
    context_notes: List[str] = Field(
        default_factory=list,
        description="Heuristic notes or discrepancies identified during deterministic passes"
    )


class AIInvestigationResult(BaseModel):
    """Structured root-cause financial diagnosis generated by the AI Investigator."""
    model_config = ConfigDict(validate_assignment=True)

    investigation_id: str = Field(..., description="Unique investigation identifier (e.g. INV-AI-0001)")
    record_id: str = Field(..., description="Target entity ID under investigation")
    scenario_type: ScenarioType = Field(..., description="Assigned scenario classification from 9-taxonomy")
    suspected_cause: str = Field(..., description="Concise financial diagnosis")
    supporting_evidence: List[str] = Field(..., description="Quantitative facts justifying the diagnosis")
    recommended_action: RecommendedAction = Field(..., description="Policy action outcome")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Final calibrated confidence score")
    top_candidates: List[CandidateScore] = Field(
        default_factory=list,
        description="Top evaluated scenario hypotheses for ambiguity analysis"
    )
    ambiguity_gap: Optional[float] = Field(
        default=None,
        description="Difference between top candidate and second candidate confidence"
    )
    reasoning_trace: str = Field(..., description="Step-by-step chain-of-thought financial calculation")
    provider_name: str = Field(..., description="LLM provider or reasoner that performed analysis")
    latency_ms: float = Field(default=0.0, description="Investigation execution latency in milliseconds")
